name: ChipUpdate
env:
      NEW_CHIP: ${{ github.event.repository.name }}
   
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  buildNewVersionChip:
    
    runs-on: windows-latest

    steps:
    
    - name: Checkout chip repo
      uses: actions/checkout@v2
      with:
       path: chip
       token: ${{ secrets.GITHUB_TOKEN }} 
       
   
    - name: Get chip dependency
      uses: actions/checkout@v2
      with: 
       token: ${{ secrets.GITHUB_TOKEN }}
       repository: JuliProg/Software
       path: references

    - name: Get CICDassist
      uses: actions/checkout@v2
      with: 
       token: ${{ secrets.GITHUB_TOKEN }}
       repository: JuliProg/CICDtools
       path: my-tools
       
    - name: Update Readmy
      working-directory: my-tools
      run : .\CICDassist.exe --renderreadmy 
      

    - name: Prepaire project enviroment 
      working-directory: my-tools
      run : .\CICDassist.exe --prebuild
   
    - name: Build new chip
      working-directory: chip
      run: dotnet build -o ..\publish
   
    - name: Publish new chip
      env: 
        MYSERVERPAT :  ${{ secrets.JP_PAT }} 
      working-directory: my-tools
      if: github.repository_owner == 'JuliProg'
      run : .\CICDassist.exe --publish "$env:NEW_CHIP" "$env:MYSERVERPAT"
    
    - name: Push repo-changes to GitHub
      shell: bash 
      working-directory: chip
      run: |
           git config --global user.email "juliprog1110.gmail.com"
           git config --global user.name "JuliProg"
           git add .
           git commit -m 'update readmy automated'
           git push origin master
           
    
           
   
