name: CICD test
env:
      NEW_CHIP: S34ML04G100BH100
      TEMPLATE_CHIP: ONFY_compliant_chip
      CHIP_DESCR: {""devManuf"":""MICRON"",""chipName"":""MT29F8G08ABABAWP"",""chipID"":""2C38002685000000"",""width"":""x8"",""bytesPP"":4096,""spareBytesPP"":224}
      
      
on:
  push:
    branches: [ master ]
    
jobs:
 
   
  Build_new_chip:
    runs-on: windows-latest 
   
    steps:
   
    - name: Checkout this chip repo
      uses: actions/checkout@v2
      with:
       path: chip
       token: ${{ secrets.GITHUB_TOKEN }} 
       
    
    - name: Get CICDassist
      uses: actions/checkout@v2
      with: 
       token: ${{ secrets.GITHUB_TOKEN }}
       repository: JuliProg/CICDtools
       path: my-tools    
       
    - name: Refactoring new repo
      working-directory: my-tools
      run : .\CICDassist.exe --create "$env:NEW_CHIP" "$env:TEMPLATE_CHIP" "$env:CHIP_DESCR"        
