name: CICD test
env:
      NEW_CHIP: "BLABLA"
      TEMPLATE_CHIP: "ONFY_compliant_chip"
      CHIP_DESCR: '{""devManuf"":""MICRON"",""bytesPP"":4096,""spareBytesPP"":224}'



      
on:
  push:
    branches: [ master ]
    
jobs:
 
   
  Test_CICD:
    runs-on: windows-latest 
   
    steps:
   
    - name: Checkout this chip repo
      uses: actions/checkout@v2
      with:
       path: chip
       token: ${{ secrets.GITHUB_TOKEN }} 
  
  
  
    - name: ls chip directory
      run: ls
      
    
    - name: Get CICDassist
      uses: actions/checkout@v2
      with: 
       token: ${{ secrets.GITHUB_TOKEN }}
       repository: JuliProg/CICDtools
       path: my-tools    
       
    - name: Refactoring new repo
      shell: bash
      working-directory: my-tools
      run : |
            ls
            .\CICDassist.exe --test "$env:NEW_CHIP" "$env:TEMPLATE_CHIP" "$env:CHIP_DESCR"        
            
